name: auto-fetch-wechat

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      test:
        required: false
        default: '1'

jobs:
  check-update:
    runs-on: ubuntu-latest
    # check if there is updates from https://aur.archlinux.org/wechat-beta-bwrap.git and fetch to repo
    steps:
      - name: 'Checkout codes' 
        uses: actions/checkout@v4
      - name: 'check updates' 
        run: |
          git config --global user.email "ntdgy@github.com"
          git config --global user.name "ntdgy"
          git remote add upstream https://aur.archlinux.org/wechat-beta-bwrap.git
          git fetch upstream
          git checkout wechat
          git merge upstream/master --allow-unrelated-histories

      # - name: Release and upload assets
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}   

      - name: GitHub Push        
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}