name: auto-fetch

on:
  # schedule:
  #   - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      branchname:
        description: '请输入要部署的分支名称:'
        required: false
        default: 'release'

jobs:
  check-update:
    runs-on: ubuntu-latest
    # check if there is updates from https://aur.archlinux.org/linuxqq.git and fetch to repo
    steps:
      - name: 'Checkout codes' 
        uses: actions/checkout@v1
      - name: 'check updates' 
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add upstream https://aur.archlinux.org/linuxqq.git
          git fetch upstream
          git checkout --track origin/master
          git merge upstream/master
                    
      - name: GitHub Push        
        uses: ad-m/github-push-action@v0.6.0
    